services:
  zookeeper:
    image: wurstmeister/zookeeper
    volumes:
      - zookeeper-data:/data
    networks:
      - traffic-net

  kafka:
    image: wurstmeister/kafka
    command: [ "start-kafka.sh" ]
    environment:
      KAFKA_CREATE_TOPICS: "events:1:1"
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kafka-data:/kafka
    depends_on:
      - zookeeper
    networks:
      - traffic-net

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: 'traffic'
      MYSQL_USER: 'jas'
      MYSQL_PASSWORD: '123'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - traffic-net

  receiver:
    build:
      context: ./Receiver
      dockerfile: Dockerfile
    environment:
      CORS_ALLOW_ALL: "no"
    depends_on:
      - kafka
    volumes:
      - ./config/receiver_config.yml:/config/receiver_config.yml
      - ./config/receiver_log_config.yml:/config/receiver_log_config.yml
      - ./logs:/logs
    networks:
      - traffic-net

  storage:
    build:
      context: ./Storage
      dockerfile: Dockerfile
    environment:
      CORS_ALLOW_ALL: "no"
    depends_on:
      - kafka
      - db
    volumes:
      - ./config/storage_config.yml:/config/storage_config.yml
      - ./config/storage_log_config.yml:/config/storage_log_config.yml
      - ./logs:/logs
    networks:
      - traffic-net

  processing:
    build:
      context: ./Processing
      dockerfile: Dockerfile
    environment:
      CORS_ALLOW_ALL: "no"
    depends_on:
      - storage
    volumes:
      - ./config/processing_config.yml:/config/processing_config.yml
      - ./config/processing_log_config.yml:/config/processing_log_config.yml
      - ./logs:/logs
      - ./data/processing:/data
    networks:
      - traffic-net

  analyzer:
    build:
      context: ./Analyzer
      dockerfile: Dockerfile
    environment:
      CORS_ALLOW_ALL: "no"
    depends_on:
      - kafka
    volumes:
      - ./config/analyzer_config.yml:/config/analyzer_config.yml
      - ./config/analyzer_log_config.yml:/config/analyzer_log_config.yml
      - ./logs:/logs
    networks:
      - traffic-net

  health-check:
    build:
      context: ./HealthCheck
      dockerfile: Dockerfile
    environment:
      CORS_ALLOW_ALL: "no"
    depends_on:
      - receiver
      - storage
      - processing
      - analyzer
    volumes:
      - ./config/health_check_config.yml:/config/health_check_config.yml
      - ./config/health_check_log_config.yml:/config/health_check_log_config.yml
      - ./logs:/logs
      - ./data/health-check:/data
    networks:
      - traffic-net

  dashboard:
    build:
      context: ./Dashboard
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - receiver
      - storage
      - processing
      - analyzer
      - health-check
    networks:
      - traffic-net

volumes:
  my-db:
  kafka-data:
  zookeeper-data:

networks:
  traffic-net:
