FROM nginx:alpine

COPY index.html /usr/share/nginx/html/
COPY style.css /usr/share/nginx/html/
COPY app.js /usr/share/nginx/html/
COPY logo.png /usr/share/nginx/html/
COPY default.conf /etc/nginx/conf.d/default.conf