version: 1
datastore:
  filename: /data/data.json

scheduler:
  interval: 7

eventstores:
  speeding:
    url: http://storage:8090/storage/events/speeding
  congestion:
    url: http://storage:8090/storage/events/congestion
